name: GitHub Pages

on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm run test:headless

    - name: Build
      run: npm run build:prod

    - name: Setup Git
      run: |
        git config --global user.email "buiquoctrieu020402@gmail.com"
        git config --global user.name "trieuquocbui"

    - name: Deploy
      if: success()
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.DEPLOY_PRIVATE_KEY }}
        publish_dir: ./
        enable_jekyll: true
